"""
Agent Chat Interface — Sprint 10D.

Provides conversational agent interface:
- Conversational agent in Streamlit
- Tool execution visible
- AI provenance display
- Citations in responses
"""

from __future__ import annotations

from datetime import datetime

import streamlit as st

# Page configuration
st.set_page_config(
    page_title="Agent Chat - Health Canada MedDev",
    page_icon="💬",
    layout="wide",
)

# Initialize session state
if "chat_messages" not in st.session_state:
    st.session_state.chat_messages = []
if "show_provenance" not in st.session_state:
    st.session_state.show_provenance = True


def get_mock_agent_response(user_message: str) -> dict:
    """Generate a mock agent response.

    In production, this would call the LangGraph agent.
    """
    # Simple keyword-based response for demo
    user_lower = user_message.lower()

    if "classify" in user_lower or "class" in user_lower:
        return {
            "response": (
                "Based on your device description, here's my analysis:\n\n"
                "**Device Classification**: Class III\n\n"
                "**Rationale**: The device monitors cardiac rhythm and provides "
                "diagnostic information that could be used to inform treatment decisions. "
                "This places it in a higher risk category.\n\n"
                "**Key Regulatory Requirements**:\n"
                "1. Medical Device Licence (MDL) required [SOR/98-282, s.26]\n"
                "2. Clinical evidence may be required [GUI-0102, Section 4]\n"
                "3. QMS certification (ISO 13485) required\n\n"
                "**Next Steps**: I recommend reviewing the gap analysis dashboard to "
                "identify any documentation gaps before submission.\n\n"
                "*Note: This assessment is for guidance purposes. Verify classification "
                "with Health Canada before submission.*"
            ),
            "tools_used": ["classify_device", "get_regulatory_requirements"],
            "citations": ["SOR/98-282, s.26", "GUI-0102, Section 4", "ISO 13485:2016"],
            "confidence": 0.85,
        }

    elif "gap" in user_lower or "readiness" in user_lower:
        return {
            "response": (
                "I've analyzed the current readiness status for your device:\n\n"
                "**Overall Readiness Score**: 72%\n\n"
                "**Critical Gaps Identified**:\n"
                "1. ⚠️ Control 'Temperature sensor' lacks verification [ISO 14971:2019, 7.2]\n"
                "2. ⚠️ Clinical evidence strength below Class III threshold [GUI-0102]\n\n"
                "**Recommendations**:\n"
                "- Complete verification testing for temperature sensor control\n"
                "- Consider additional clinical data to strengthen evidence package\n"
                "- Review unmitigated hazards in risk management file\n\n"
                "*Gap findings are generated by deterministic rules citing regulatory sources.*"
            ),
            "tools_used": ["evaluate_gaps", "get_readiness_score"],
            "citations": ["ISO 14971:2019, 7.2", "GUI-0102"],
            "confidence": 0.92,
        }

    elif "pathway" in user_lower or "timeline" in user_lower:
        return {
            "response": (
                "Here's the regulatory pathway for your Class III device:\n\n"
                "**Estimated Timeline**: 90-120 days\n\n"
                "**Step 1: MDEL Application** (~15 days)\n"
                "- Establishment licence required before importing [SOR/98-282, Part 3]\n"
                "- Fee: ~$7,000 CAD\n\n"
                "**Step 2: MDL Application** (~75 days)\n"
                "- Complete application per GUI-0098\n"
                "- Fee: ~$21,000 CAD\n\n"
                "**Step 3: Post-Market Requirements**\n"
                "- Annual licence fee\n"
                "- Mandatory problem reporting [SOR/98-282, s.59]\n\n"
                "*Timelines are estimates based on Health Canada service standards.*"
            ),
            "tools_used": ["get_pathway_advisor", "get_fee_schedule"],
            "citations": ["SOR/98-282, Part 3", "GUI-0098", "SOR/98-282, s.59"],
            "confidence": 0.88,
        }

    elif "evidence" in user_lower or "clinical" in user_lower:
        return {
            "response": (
                "I've reviewed your clinical evidence portfolio:\n\n"
                "**Portfolio Summary**:\n"
                "- 5 clinical studies on file\n"
                "- Weighted quality score: 68%\n"
                "- Class III threshold: 60% ✅\n\n"
                "**Strongest Evidence**:\n"
                "- Multicenter RCT (n=250): Score 0.92\n"
                "- Prospective cohort (n=500): Score 0.78\n\n"
                "**Recommendation**:\n"
                "Your evidence package meets the minimum threshold for Class III. "
                "Consider adding post-market registry data to strengthen the package.\n\n"
                "*Evidence scoring based on GUI-0102 hierarchy.*"
            ),
            "tools_used": ["get_clinical_portfolio", "assess_evidence_strength"],
            "citations": ["GUI-0102, Section 3.2", "GUI-0102, Section 4.1"],
            "confidence": 0.90,
        }

    else:
        return {
            "response": (
                "I'm here to help with Health Canada medical device regulatory questions. "
                "I can assist with:\n\n"
                "- **Device Classification**: Determine your device class\n"
                "- **Gap Analysis**: Identify regulatory documentation gaps\n"
                "- **Pathway Guidance**: Understand regulatory timelines and fees\n"
                "- **Clinical Evidence**: Review evidence requirements\n\n"
                "What would you like help with today?\n\n"
                "*All responses cite regulatory sources. For official guidance, "
                "consult Health Canada directly.*"
            ),
            "tools_used": [],
            "citations": [],
            "confidence": 1.0,
        }


def render_message(message: dict) -> None:
    """Render a chat message with optional provenance."""
    role = message["role"]
    content = message["content"]

    with st.chat_message(role):
        st.markdown(content)

        if role == "assistant" and st.session_state.show_provenance:
            metadata = message.get("metadata", {})

            if metadata.get("tools_used"):
                with st.expander("🔧 Tools Used"):
                    for tool in metadata["tools_used"]:
                        st.markdown(f"- `{tool}`")

            if metadata.get("citations"):
                with st.expander("📚 Citations"):
                    for citation in metadata["citations"]:
                        st.code(citation, language=None)

            if metadata.get("confidence"):
                st.caption(f"Confidence: {metadata['confidence'] * 100:.0f}%")


def main():
    """Main agent chat page."""
    st.title("💬 Regulatory Agent Chat")
    st.markdown("*Conversational AI assistant for Health Canada medical device regulations*")

    # Sidebar options
    with st.sidebar:
        st.subheader("Chat Settings")
        st.session_state.show_provenance = st.checkbox(
            "Show AI Provenance",
            value=True,
            help="Display tools used and citations for each response",
        )

        st.divider()

        if st.button("🗑️ Clear Chat"):
            st.session_state.chat_messages = []
            st.rerun()

        st.divider()

        st.markdown("### Quick Prompts")
        if st.button("📋 Classify my device"):
            st.session_state.chat_messages.append(
                {"role": "user", "content": "Can you help classify my cardiac monitoring device?"}
            )
            st.rerun()
        if st.button("📊 Check readiness"):
            st.session_state.chat_messages.append(
                {"role": "user", "content": "What is the gap analysis for my device?"}
            )
            st.rerun()
        if st.button("🗺️ Get pathway"):
            st.session_state.chat_messages.append(
                {"role": "user", "content": "What is the regulatory pathway and timeline?"}
            )
            st.rerun()

    # Display chat history
    for message in st.session_state.chat_messages:
        render_message(message)

    # Chat input
    if prompt := st.chat_input("Ask about Health Canada regulations..."):
        # Add user message
        st.session_state.chat_messages.append({"role": "user", "content": prompt})

        # Get agent response
        with st.spinner("Thinking..."):
            response = get_mock_agent_response(prompt)

        # Add assistant message with metadata
        st.session_state.chat_messages.append(
            {
                "role": "assistant",
                "content": response["response"],
                "metadata": {
                    "tools_used": response["tools_used"],
                    "citations": response["citations"],
                    "confidence": response["confidence"],
                    "timestamp": datetime.utcnow().isoformat(),
                },
            }
        )

        st.rerun()

    # Empty state
    if not st.session_state.chat_messages:
        st.info(
            "👋 Welcome! I'm your Health Canada regulatory assistant. "
            "Ask me about device classification, regulatory pathways, "
            "gap analysis, or evidence requirements."
        )
        st.markdown(
            """
        **Example Questions:**
        - "Can you classify my cardiac monitoring device?"
        - "What gaps exist in my regulatory documentation?"
        - "What is the pathway for a Class III device?"
        - "How strong is my clinical evidence package?"
        """
        )

    # Footer
    st.divider()
    st.caption(
        "⚠️ This assistant provides guidance based on Health Canada regulations. "
        "All responses cite regulatory sources. For official submissions, "
        "consult qualified regulatory professionals. "
        "[Per CLAUDE.md: Human-in-the-loop required for all AI outputs]"
    )


if __name__ == "__main__":
    main()
