"""
Regulatory Twin Core Entity Models.

Pydantic models for the 10 regulatory twin tables:
  intended_uses, claims, hazards, harms, risk_controls,
  verification_tests, validation_tests, evidence_items,
  labeling_assets, submission_targets

Design:
  - Mirror DB schema exactly (same field names, same constraints)
  - Validators enforce CHECK constraint values in Python
  - .to_db_dict() for persistence (excludes None, converts UUID to str)
  - @classmethod from_db_row() for reading from DB rows
  - All IDs are Optional[uuid] (generated by DB on insert)

Sprint 1b — 2026-02-07
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field

# =========================================================================
# Shared types (matching DB CHECK constraints exactly)
# =========================================================================

ClaimStatus = Literal["draft", "under_review", "accepted", "rejected", "superseded"]
ClaimType = Literal[
    "safety",
    "performance",
    "usability",
    "biocompatibility",
    "sterility",
    "shelf_life",
    "software_performance",
    "other",
]

HazardCategory = Literal[
    "electrical",
    "biological",
    "chemical",
    "mechanical",
    "thermal",
    "radiation",
    "software",
    "use_error",
    "cybersecurity",
    "environmental",
    "other",
]

Severity = Literal["negligible", "marginal", "critical", "catastrophic"]
Probability = Literal["improbable", "remote", "occasional", "probable", "frequent"]
RiskLevel = Literal["low", "medium", "high", "unacceptable"]

HarmType = Literal[
    "injury",
    "death",
    "misdiagnosis",
    "delayed_treatment",
    "unnecessary_treatment",
    "infection",
    "tissue_damage",
    "psychological",
    "financial",
    "other",
]

ControlType = Literal["inherent_safety", "protective_measure", "information_for_safety"]
ImplementationStatus = Literal["planned", "in_progress", "implemented", "verified", "retired"]

VerificationTestType = Literal[
    "bench",
    "software",
    "biocompatibility",
    "electrical_safety",
    "emc",
    "sterilization",
    "packaging",
    "shelf_life",
    "cybersecurity",
    "other",
]

ValidationTestType = Literal[
    "usability",
    "clinical_investigation",
    "clinical_evaluation",
    "simulated_use",
    "formative",
    "summative",
    "other",
]

PassFail = Literal["pass", "fail", "conditional", "pending"]

EvidenceType = Literal[
    "test_report",
    "literature_review",
    "clinical_data",
    "standard_reference",
    "predicate_comparison",
    "risk_analysis",
    "design_output",
    "manufacturing_record",
    "post_market_data",
    "expert_opinion",
    "other",
]
EvidenceStrength = Literal["strong", "moderate", "weak", "insufficient"]
EvidenceStatus = Literal["draft", "under_review", "accepted", "rejected", "superseded"]

LabelingAssetType = Literal[
    "ifu",
    "label",
    "packaging",
    "e_labeling",
    "quick_reference",
    "patient_information",
    "surgical_technique",
    "other",
]
RegulatoryMarket = Literal["CA", "US", "EU", "UK", "AU", "JP", "CN", "other"]

RegulatoryBody = Literal["health_canada", "fda", "eu_mdr", "mhra", "tga", "pmda", "nmpa", "other"]
SubmissionType = Literal[
    "mdl", "510k", "de_novo", "pma", "ce_mark", "ukca", "tga_inclusion", "shonin", "other"
]
SubmissionStatus = Literal[
    "planning", "preparing", "submitted", "under_review", "approved", "rejected", "withdrawn"
]


# =========================================================================
# Base class with shared serialization
# =========================================================================


class RegulatoryTwinBase(BaseModel):
    """Base for all regulatory twin models."""

    def to_db_dict(self) -> dict[str, Any]:
        """Convert to dict for DB insert, excluding None values and converting UUIDs."""
        data: dict[str, Any] = {}
        for key, value in self.model_dump().items():
            if value is None:
                continue
            if isinstance(value, UUID):
                data[key] = str(value)
            elif isinstance(value, datetime | date):
                data[key] = value.isoformat()
            elif isinstance(value, list):
                data[key] = value
            else:
                data[key] = value
        return data

    @classmethod
    def from_db_row(cls, row: dict[str, Any]) -> RegulatoryTwinBase:
        """Create model instance from a DB row dict."""
        return cls(**row)


# =========================================================================
# 1. IntendedUse
# =========================================================================


class IntendedUse(RegulatoryTwinBase):
    """Intended use statement for a device version (ISO 14971 / HC)."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    statement: str = Field(..., min_length=1)
    indications: list[str] = Field(default_factory=list)
    contraindications: list[str] = Field(default_factory=list)
    target_population: str | None = None
    use_environment: str | None = None
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 2. Claim
# =========================================================================


class Claim(RegulatoryTwinBase):
    """A regulatory claim about a device (safety, performance, etc.)."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    claim_type: ClaimType
    statement: str = Field(..., min_length=1)
    evidence_basis: str | None = None
    status: ClaimStatus = "draft"
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 3. Hazard
# =========================================================================


class Hazard(RegulatoryTwinBase):
    """A hazard identified in risk analysis (ISO 14971)."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    hazard_category: HazardCategory
    description: str = Field(..., min_length=1)
    foreseeable_sequence: str | None = None
    severity: Severity | None = None
    probability: Probability | None = None
    risk_level_pre: RiskLevel | None = None
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 4. Harm
# =========================================================================


class Harm(RegulatoryTwinBase):
    """A harm resulting from a hazard (ISO 14971)."""

    id: UUID | None = None
    organization_id: UUID
    hazard_id: UUID
    harm_type: HarmType
    description: str = Field(..., min_length=1)
    severity: Severity
    affected_population: str | None = None
    created_by: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 5. RiskControl
# =========================================================================


class RiskControl(RegulatoryTwinBase):
    """A risk control measure for a hazard (ISO 14971 hierarchy)."""

    id: UUID | None = None
    organization_id: UUID
    hazard_id: UUID
    control_type: ControlType
    description: str = Field(..., min_length=1)
    risk_level_post: RiskLevel | None = None
    implementation_status: ImplementationStatus = "planned"
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 6. VerificationTest
# =========================================================================


class VerificationTest(RegulatoryTwinBase):
    """A verification test (design verification, ISO 13485)."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    test_type: VerificationTestType
    title: str = Field(..., min_length=1)
    protocol_ref: str | None = None
    acceptance_criteria: str = Field(..., min_length=1)
    result_summary: str | None = None
    pass_fail: PassFail | None = None
    tested_at: datetime | None = None
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 7. ValidationTest
# =========================================================================


class ValidationTest(RegulatoryTwinBase):
    """A validation test (design validation, ISO 13485)."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    test_type: ValidationTestType
    title: str = Field(..., min_length=1)
    protocol_ref: str | None = None
    acceptance_criteria: str = Field(..., min_length=1)
    result_summary: str | None = None
    pass_fail: PassFail | None = None
    participant_count: int | None = Field(default=None, ge=0)
    tested_at: datetime | None = None
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 8. EvidenceItem
# =========================================================================


class EvidenceItem(RegulatoryTwinBase):
    """An evidence item supporting a claim or control."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    evidence_type: EvidenceType
    title: str = Field(..., min_length=1)
    description: str | None = None
    source_ref: str | None = None
    artifact_id: UUID | None = None
    strength: EvidenceStrength = "moderate"
    status: EvidenceStatus = "draft"
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 9. LabelingAsset
# =========================================================================


class LabelingAsset(RegulatoryTwinBase):
    """A labeling asset (IFU, label, packaging) for a device."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    asset_type: LabelingAssetType
    title: str = Field(..., min_length=1)
    content_ref: str | None = None
    language: str = "en"
    regulatory_market: RegulatoryMarket | None = None
    artifact_id: UUID | None = None
    status: EvidenceStatus = "draft"
    created_by: UUID | None = None
    version: int = Field(default=1, ge=1)
    supersedes_id: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# 10. SubmissionTarget
# =========================================================================


class SubmissionTarget(RegulatoryTwinBase):
    """A regulatory submission target for a device."""

    id: UUID | None = None
    organization_id: UUID
    device_version_id: UUID
    regulatory_body: RegulatoryBody
    submission_type: SubmissionType
    target_date: date | None = None
    status: SubmissionStatus = "planning"
    reference_number: str | None = None
    created_by: UUID | None = None
    created_at: datetime | None = None


# =========================================================================
# Registry: all models by table name (useful for generic operations)
# =========================================================================

TWIN_MODEL_REGISTRY: dict[str, type] = {
    "intended_uses": IntendedUse,
    "claims": Claim,
    "hazards": Hazard,
    "harms": Harm,
    "risk_controls": RiskControl,
    "verification_tests": VerificationTest,
    "validation_tests": ValidationTest,
    "evidence_items": EvidenceItem,
    "labeling_assets": LabelingAsset,
    "submission_targets": SubmissionTarget,
}
